import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { getPrincipalFromRequest } from "@/lib/auth";
import { query, transaction } from "@/lib/db";
import { isTrustedBrowserMutation } from "@/lib/csrf";

const schema=z.object({organizationId:z.string().uuid(),templateCode:z.string().min(2).max(100),displayName:z.string().min(2).max(160),channel:z.enum(['SMS','EMAIL','INTERNAL_NOTE']),purpose:z.string().min(2).max(100),version:z.string().min(1).max(40),bodyTemplate:z.string().min(1).max(4000),approved:z.boolean().default(false)});
export async function GET(request:NextRequest){const p=await getPrincipalFromRequest(request);if(!p)return NextResponse.json({error:'Unauthorized'},{status:401});const orgIds=p.memberships.map(m=>m.organizationId);const r=await query(`SELECT id::text,organization_id::text,template_code,display_name,channel,purpose,version,body_template,approved,active,updated_at::text FROM communication_templates WHERE organization_id IS NULL OR organization_id=ANY($1::uuid[]) ORDER BY display_name,version DESC LIMIT 250`,[orgIds]);return NextResponse.json({items:r.rows});}
export async function POST(request:NextRequest){if(!isTrustedBrowserMutation(request))return NextResponse.json({error:'Untrusted origin'},{status:403});const p=await getPrincipalFromRequest(request);if(!p)return NextResponse.json({error:'Unauthorized'},{status:401});const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success||!p.memberships.some(m=>m.organizationId===parsed.data.organizationId))return NextResponse.json({error:'Invalid request'},{status:422});return transaction(async c=>{const d=parsed.data;const r=await c.query<{id:string}>(`INSERT INTO communication_templates(organization_id,template_code,display_name,channel,purpose,version,body_template,approved,approved_by_user_id,approved_at,created_by_user_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,CASE WHEN $8 THEN $9 ELSE NULL END,CASE WHEN $8 THEN now() ELSE NULL END,$9) RETURNING id::text`,[d.organizationId,d.templateCode,d.displayName,d.channel,d.purpose,d.version,d.bodyTemplate,d.approved,p.userId]);await c.query(`INSERT INTO audit_events(organization_id,actor_type,actor_id,event_type,entity_type,entity_id,metadata) VALUES($1,'USER',$2,'COMMUNICATION_TEMPLATE_CREATED','COMMUNICATION_TEMPLATE',$3,$4::jsonb)`,[d.organizationId,p.userId,r.rows[0].id,JSON.stringify({templateCode:d.templateCode,channel:d.channel,purpose:d.purpose,version:d.version,approved:d.approved})]);return NextResponse.json({ok:true,id:r.rows[0].id});});}
