import type {PoolClient} from "pg";
export async function calculateFirmCapacity(client:PoolClient,firmId:string){
  const profile=(await client.query<any>(`SELECT daily_capacity,monthly_capacity,active FROM law_firm_profiles WHERE organization_id=$1`,[firmId])).rows[0];if(!profile)return null;
  const counts=(await client.query<any>(`SELECT COUNT(*) FILTER(WHERE fa.assigned_at>=date_trunc('day',now()))::int daily_used,COUNT(*) FILTER(WHERE fa.assigned_at>=date_trunc('month',now()))::int monthly_used,COUNT(*) FILTER(WHERE m.status NOT IN ('ARCHIVED','FIRM_DECLINED','CLAIMANT_DECLINED','DUPLICATE','FRAUD_TEST'))::int active_assignment_count FROM firm_assignments fa JOIN matters m ON m.id=fa.matter_id WHERE fa.law_firm_organization_id=$1`,[firmId])).rows[0];
  const pending=(await client.query<any>(`SELECT COUNT(*)::int c FROM law_firm_review_instances WHERE law_firm_organization_id=$1 AND firm_disposition='PENDING'`,[firmId])).rows[0]?.c??0;
  const dailyRemaining=profile.daily_capacity==null?null:Math.max(0,profile.daily_capacity-counts.daily_used);const monthlyRemaining=profile.monthly_capacity==null?null:Math.max(0,profile.monthly_capacity-counts.monthly_used);const finite=[dailyRemaining,monthlyRemaining].filter((v):v is number=>v!==null);const remaining=finite.length?Math.min(...finite):null;const accepting=Boolean(profile.active)&&(remaining===null||remaining>0);
  await client.query(`INSERT INTO law_firm_capacity_snapshots(law_firm_organization_id,snapshot_date,daily_capacity,daily_used,monthly_capacity,monthly_used,accepting_new_matters,pending_review_count,active_assignment_count,capacity_remaining,calculated_at) VALUES($1,current_date,$2,$3,$4,$5,$6,$7,$8,$9,now()) ON CONFLICT(law_firm_organization_id,snapshot_date) DO UPDATE SET daily_capacity=EXCLUDED.daily_capacity,daily_used=EXCLUDED.daily_used,monthly_capacity=EXCLUDED.monthly_capacity,monthly_used=EXCLUDED.monthly_used,accepting_new_matters=EXCLUDED.accepting_new_matters,pending_review_count=EXCLUDED.pending_review_count,active_assignment_count=EXCLUDED.active_assignment_count,capacity_remaining=EXCLUDED.capacity_remaining,calculated_at=now()`,[firmId,profile.daily_capacity,counts.daily_used,profile.monthly_capacity,counts.monthly_used,accepting,pending,counts.active_assignment_count,remaining]);
  return{dailyCapacity:profile.daily_capacity,dailyUsed:counts.daily_used,monthlyCapacity:profile.monthly_capacity,monthlyUsed:counts.monthly_used,pendingReviewCount:pending,activeAssignmentCount:counts.active_assignment_count,capacityRemaining:remaining,acceptingNewMatters:accepting};
}
